# Generated by Django 5.1.7 on 2025-03-29 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('collected_kg', models.FloatField(help_text='Kg of collected trash')),
                ('cleaned_all', models.BooleanField(default=False, help_text='Has the site been cleaned up completely?')),
                ('before_image', models.ImageField(blank=True, help_text='Before cleanup image', null=True, upload_to='activity_images/before/')),
                ('after_image', models.ImageField(blank=True, help_text='After cleanup image', null=True, upload_to='activity_images/after/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrashPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('trash_level', models.IntegerField(choices=[(1, 'Light'), (2, 'Moderate'), (3, 'Extreme')], default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AddField(
            model_name='activity',
            name='trash_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleanups', to='api.trashplace'),
        ),
    ]
