# Generated by Django 5.1.7 on 2025-03-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_activity_trashplace_delete_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashplace',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the trash place still there?'),
        ),
    ]
